### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by PawarenessC** [DragMineTeam/DragMine#5]
突然の質問すみません。
先日公式PMMPで様々は動きがあり、
色々な変更がありましたが、
こちらのサーバソフトもそれに合わせて、
同じ変更を行いますでしょうか?

**Comment by towa0131** [comment]
@Xxawareness まだなんとも言えない状態です。
しかし将来的に公式に合わせる可能性は0ではないです。

**Comment by PawarenessC** [comment]
ご回答ありがとうございましたm(_ _)m
